(* File auto-generated by obus-gen-interface, DO NOT EDIT.
   Well OK, I edited it a bit: to include only the bits we need and avoid ppx.  *)

let (let*) = Lwt.bind
let return = Lwt.return

module Login1_interfaces = struct
  open OBus_value
  open OBus_value.C
  open OBus_member
  module Org_freedesktop_login1_Manager = struct
    let interface = "org.freedesktop.login1.Manager"
    let m_GetSession = {
      Method.interface = interface;
      Method.member = "GetSession";
      Method.i_args = (arg1
                         (Some "session_id", basic_string));
      Method.o_args = (arg1
                         (Some "object_path", basic_object_path));
      Method.annotations = [];
    }
    let m_GetSessionByPID = {
      Method.interface = interface;
      Method.member = "GetSessionByPID";
      Method.i_args = (arg1
                         (Some "pid", basic_uint32));
      Method.o_args = (arg1
                         (Some "object_path", basic_object_path));
      Method.annotations = [];
    }
  end

  module Org_freedesktop_login1_Session = struct
    let interface = "org.freedesktop.login1.Session"
    let m_TakeControl = {
      Method.interface = interface;
      Method.member = "TakeControl";
      Method.i_args = (arg1
                         (Some "force", basic_boolean));
      Method.o_args = (arg0);
      Method.annotations = [];
    }
    let m_TakeDevice = {
      Method.interface = interface;
      Method.member = "TakeDevice";
      Method.i_args = (arg2
                         (Some "major", basic_uint32)
                         (Some "minor", basic_uint32));
      Method.o_args = (arg2
                         (Some "fd", basic_unix_fd)
                         (Some "inactive", basic_boolean));
      Method.annotations = [];
    }
    let m_ReleaseDevice = {
      Method.interface = interface;
      Method.member = "ReleaseDevice";
      Method.i_args = (arg2
                         (Some "major", basic_uint32)
                         (Some "minor", basic_uint32));
      Method.o_args = (arg0);
      Method.annotations = [];
    }
    let m_ReleaseControl = {
      Method.interface = interface;
      Method.member = "ReleaseControl";
      Method.i_args = (arg0);
      Method.o_args = (arg0);
      Method.annotations = [];
    }
  end
end

module Login1_client = struct
  open Login1_interfaces

  module Org_freedesktop_login1_Manager = struct
    open Org_freedesktop_login1_Manager

    let get_session proxy ~session_id =
      let* (context, object_path) = OBus_method.call_with_context m_GetSession proxy session_id in
      let object_path = (fun x -> OBus_proxy.make ~peer:(OBus_context.sender context) ~path:x) object_path in
      return object_path

    let get_session_by_pid proxy ~pid =
      let pid = Int32.of_int pid in
      let* (context, object_path) = OBus_method.call_with_context m_GetSessionByPID proxy pid in
      let object_path = (fun x -> OBus_proxy.make ~peer:(OBus_context.sender context) ~path:x) object_path in
      return object_path
  end

  module Org_freedesktop_login1_Session = struct
    open Org_freedesktop_login1_Session

    let take_control proxy ~force =
      OBus_method.call m_TakeControl proxy force

    let release_control proxy =
      OBus_method.call m_ReleaseControl proxy ()

    let take_device proxy ~major ~minor =
      let major = Int32.of_int major in
      let minor = Int32.of_int minor in
      OBus_method.call m_TakeDevice proxy (major, minor)

    let release_device proxy ~major ~minor =
      let major = Int32.of_int major in
      let minor = Int32.of_int minor in
      OBus_method.call m_ReleaseDevice proxy (major, minor)
  end
end
