(* The landscape is a [Ubo.land_view_size] grid that flies along under the ship
   and is large enough that the player can't see the edges.

   Each vertex has its x and y components generated automatically by the shader code
   based on its ID, and gets its z component by sampling the height map. *)

module Vkt = Vk.Types
module A = Vulkan.A

(* Although the vertices are generated by the shader, the indices are fixed
   and we pregenerate them and upload to the GPU, which seems to be the easiest
   way to do it. *)
module Indices = struct
  type t = {
    buffer : Vkt.Buffer.t;
    index_count : int;
  }

  (* Draw the map tiles as a triangle strip.
     The layout of the vertices is:
     0 1 2
     3 4 5
     6 7 8
     All triangles need to be anti-clockwise. This is so that the culling works.
     The first row starts with the triangle (0, 3, 1), for example. *)
  let v =
    let i = Dynarray.create () in
    let add v = Dynarray.add_last i v in
    let view_width, view_height = Ubo.land_view_size in
    assert (view_width * view_height < 0xffff);         (* Or we'd overflow the 16-bit indices *)
    for row = 0 to view_height - 2 do
      let row_tl = view_width * row in
      for col = 0 to view_width - 1 do
        let top = row_tl + col in
        let bot = top + view_width in
        add top;
        add bot;
      done;
      add (-1);         (* Start a new strip *)
    done;
    Dynarray.to_list i
    |> List.map Unsigned.UInt16.of_int
    |> A.of_list Ctypes.uint16_t

  (* Copy to memory shared with the GPU *)
  let allocate ~sw ~device =
    let size = A.sizeof v in
    let buffer =
      Vulkan.Buffer.create ~sw device size
        ~usage:Vkt.Buffer_usage_flags.index_buffer
        ~properties:Vkt.Memory_property_flags.(host_visible + host_coherent)
    in
    Memcpy.map_and_copy v ~dst:buffer;
    {
      buffer = buffer.buffer;
      index_count = A.length v;
    }

  (* Record commands to draw the landscape. *)
  let record t cmd =
    let { buffer; index_count } = t in
    Vulkan.Cmd.bind_index_buffer cmd buffer (Vkt.Device_size.of_int 0) Uint16;
    Vulkan.Cmd.draw_indexed cmd
      ~first_index:0 ~index_count
      ~first_instance:0 ~instance_count:1
      ~vertex_offset:0
end

let shader_code = [%blob "./landscape.spv"]

let bindings = Vulkan.Binding.[
  v 0 Uniform_buffer         Vkt.Shader_stage_flags.(vertex + fragment);
  v 1 Combined_image_sampler Vkt.Shader_stage_flags.vertex;     (* Height map *)
  v 2 Combined_image_sampler Vkt.Shader_stage_flags.fragment;   (* Tiles *)
]

(* Used to sample the height map or tile map (no interpolation needed; it's just an array lookup). *)
let sampler ~sw device =
  Vulkan.Device.create_sampler ~sw device @@
  Vkt.Sampler_create_info.make ()
    ~min_filter:Vkt.Filter.Nearest
    ~mag_filter:Vkt.Filter.Nearest
    ~flags:Vkt.Sampler_create_flags.empty
    ~mipmap_mode:Nearest
    ~address_mode_u:Clamp_to_edge
    ~address_mode_v:Clamp_to_edge
    ~address_mode_w:Clamp_to_edge
    ~mip_lod_bias:0.0
    ~anisotropy_enable:false
    ~max_anisotropy:1.0
    ~compare_enable:false
    ~compare_op:Always
    ~min_lod:0.0
    ~max_lod:0.0
    ~border_color:Vkt.Border_color.Int_opaque_black
    ~unnormalized_coordinates:true

let no_stencil_op = Vkt.Stencil_op_state.make
    ~fail_op:Vkt.Stencil_op.Zero
    ~pass_op:Vkt.Stencil_op.Zero
    ~depth_fail_op:Vkt.Stencil_op.Zero
    ~compare_op:Vkt.Compare_op.Never
    ~compare_mask:0
    ~write_mask:0
    ~reference:0

let write_depth_buffer = Vkt.Pipeline_depth_stencil_state_create_info.make ()
    ~depth_test_enable:true             (* Badly named: we're not actually testing *)
    ~depth_compare_op:Always            (* We draw back-to-front so there's no need to test *)
    ~depth_write_enable:true            (* But we do store the depth, as the ship may go behind a hill *)
    ~depth_bounds_test_enable:false
    ~stencil_test_enable:false
    ~front:no_stencil_op
    ~back:no_stencil_op
    ~min_depth_bounds:0.0
    ~max_depth_bounds:0.0

type t = (Vulkan.Cmd.t -> unit) Double.t

let create ~sw ~device ~ubo ~render_pass =
  let command_pool = Vulkan.Cmd.create_pool ~sw device in
  let sampler = sampler ~sw device in
  let map_heights =
    let image_view = Map.create_heights ~sw ~command_pool ~device in
    Vkt.Descriptor_image_info.make ~image_view ~sampler
      ~image_layout:Shader_read_only_optimal
  in
  let map_tiles =
    let image_view = Map.create_tiles ~sw ~command_pool ~device in
    Vkt.Descriptor_image_info.make ~image_view ~sampler
      ~image_layout:Shader_read_only_optimal
  in
  let rasterizer = Vkt.Pipeline_rasterization_state_create_info.make ()
      ~depth_clamp_enable:false
      ~rasterizer_discard_enable:false
      ~polygon_mode:Fill
      ~line_width:1.0
      ~cull_mode:Vkt.Cull_mode_flags.back
      ~front_face:Counter_clockwise
      ~depth_bias_enable:false
      ~depth_bias_constant_factor:0.0
      ~depth_bias_clamp:0.0
      ~depth_bias_slope_factor:0.0
  in
  let max_sets = 2 in
  let layout = Vulkan.Descriptor_set.make_layout ~sw device bindings in
  let pipeline_layout =
    Vulkan.Device.create_pipeline_layout ~sw device @@
    Vkt.Pipeline_layout_create_info.make ()
      ~set_layouts:(Vkt.Descriptor_set_layout.array [layout])
  in
  let pool = Vulkan.Descriptor_set.create_pool ~sw device ~max_sets [
      Uniform_buffer, max_sets;
      Combined_image_sampler, max_sets * 2;
    ] in
  let descriptor_sets = Vulkan.Descriptor_set.allocate pool layout max_sets in
  let pipeline =
    let shader = Vulkan.Shader.load ~sw device shader_code in
    Vulkan.Pipeline.make ~sw ~device ~render_pass ()
      ~topology:Triangle_strip
      ~primitive_restart_enable:true
      ~rasterizer
      ~layout:pipeline_layout
      ~depth_stencil_state:write_depth_buffer
      ~stages:[
          shader "vertLandscape" Vkt.Shader_stage_flags.vertex;
          shader "fragLandscape" Vkt.Shader_stage_flags.fragment;
        ]
  in
  let vertex_buffer = Indices.allocate ~sw ~device in
  Double.init (fun side ->
      let descriptor_set = A.get descriptor_sets (Double.to_index side) in
      let ubo = Double.get ubo side in
      Vulkan.Descriptor_set.update ~device [
        Vulkan.Descriptor_set.write descriptor_set Uniform_buffer         [ubo.Ubo.info] ~dst_binding:0 ~dst_array_element:0;
        Vulkan.Descriptor_set.write descriptor_set Combined_image_sampler [map_heights]  ~dst_binding:1 ~dst_array_element:0;
        Vulkan.Descriptor_set.write descriptor_set Combined_image_sampler [map_tiles]    ~dst_binding:2 ~dst_array_element:0;
      ];
      fun cmd ->
        Vulkan.Cmd.bind_pipeline cmd ~stage:Graphics pipeline;
        Vulkan.Cmd.bind_descriptor_sets cmd [descriptor_set]
          ~pipeline_bind_point:Graphics
          ~layout:pipeline_layout
          ~first_set:0;
        Indices.record vertex_buffer cmd
    )

let draw t side cmd = Double.get t side cmd
